### ISSUE TITLE
[Gnome 47] Session save errors, weird session dirs; window positions not saved (maybe user/xdotool error?)

### ISSUE THREAD

**Issue by scarlion1** [nlpsuge/gnome-shell-extension-another-window-session-manager#116]
I feel like I posted about this already but maybe I just imagined I did in some sleep deprived state... maybe i started to but then must have rebooted before posting, coz i can't find anything 😅 
<h3>but,</h3>

when forced to run in Gnome 47, _AWSM_ constantly is throwing errors about unable to save the session.  I turned on debugging and verbose logging, and I see errors such as our favourite type, undefined ones!

```python
[ERROR  ][Another window session manager] undefined: Error: Cannot save session: /home/scar/.config/another-window-session-manager/currentSession/summary.json
Stack trace:
CommonError@file:///home/scar/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/utils/CommonError.js:23:9
_saveSessionConfigAsync/</this._saveSessionIdleId</<@file:///home/scar/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/saveSession.js:469:32
@resource:///org/gnome/shell/ui/init.js:21:20
Caused by: Gio.IOErrorEnum: Operation was cancelled
```
Yet, the `summary.json` is still saved often, as there are also many `[INFO   ][Another window session manager] Session summary.json saved` messages.

<h3>Also,</h3>

the `currentSession` dir is a mess, any time there is a slash in a window title, it creates a new subdirectory instead of escaping the slash, is that intended?  For example, the saved session for this window, when i was reading the other issue, was:
`/home/scar/.config/another-window-session-manager/currentSession/firefox/0x2000157 (Support Gnome 47 · Issue #110 · nlpsuge/gnome-shell-extension-another-window-session-manager — Mozilla Firefox).json`
which is the directory: `.../0x2000157 (Support Gnome 47 · Issue #110 · nlpsuge/`
containing the file: `gnome-shell-extension-another-window-session-manager — Mozilla Firefox).json`

or spacefm is fun when i navigate thru `/usr/share/gnome-shell/extensions/`:
```python
$ pwd
/home/scar/.config/another-window-session-manager/currentSession
$ tree Spacefm/
Spacefm/
└── 0x3400007 (
    ├── home
    │   ├── scar
    │   └── scar).json
    ├── ).json
    ├── usr
    │   ├── share
    │   │   ├── gnome-shell
    │   │   │   ├── extensions
    │   │   │   │   └── apps-menu@gnome-shell-extensions.gcampax.github.com).json
    │   │   │   └── extensions).json
    │   │   └── gnome-shell).json
    │   └── share).json
    └── usr).json
```

Right now I would love for my windows' sizes and positions to be remembered but that's not happening.  Is there more to configure after turning on "Close by rules"? because there's nothing defined underneath that..

Will it work with `xdotool version 3.20160805.1`?  Because i'm an x11 user and the repo version of `ydotool` is <<1.0 and thus not installed.  I'd rather use `xdotool` than mess with compiling `ydotool` if possible.  Could that be root cause of all this, though?

Best Regards
<hr>

```python
Debian trixie/testing
Linux 6.12.12-1 (2025-02-02) x86_64
GNOME Shell 47.3/X11
Extension: ver 49, Shell-Version "47" added to metadata.json
```

**Comment by scarlion1** [comment]
> it creates a new subdirectory instead of escaping the slash, is that intended?  

I'm guessing not, because, after a while, I'm seeing errors like the following:

```python
[ERROR  ][Another window session manager] undefined: Error: Cannot remove '/home/scar/.config/another-window-session-manager/currentSession/Gnome-terminal/0x2400006 (scar@RemoteHost(pts': Is a directory
Stack trace:
removeFile@utils/fileUtils.js:263:23
_removeOrphanSessionConfigs/<@openWindowsTracker.js:423:31
listAllSessions@utils/fileUtils.js:179:29
async*_removeOrphanSessionConfigs@openWindowsTracker.js:419:23
_cleanUpSessionFileByWindow@openWindowsTracker.js:402:14
_connectSignalsToCleanUpSessionFile/unmanagingId<@openWindowsTracker.js:368:22
@resource:///org/gnome/shell/ui/init.js:21:20
```

which comes from an SSH session to "RemoteHost", which updates the title of the Gnome Terminal window to include the tty it's connected to, which is parsed from the output of `tty` command and thus has forward slashes in it.
